version: '3'
services:
  backend:
    image: ggkioka/asgard-rest
    deploy:
      replicas: 2
    restart: always
  frontend:
    image: ggkioka/asgard-web
    restart: always
    links:
      - backend
    ports:
      - "5580:80"